### ISSUE TITLE
Travis builds fail due to go-git

### ISSUE THREAD

**Issue by aloupfor** [dunglas/calavera#20]
I saw that the Travis builds failed on this PR: https://github.com/dunglas/calavera/pull/19.
I looked at the logs and saw:
```
extractor/git.go:41:15: undefined: git.NewFilesystemRepository
```

Currently go-git comes from
```
gopkg.in/src-d/go-git.v4
````

I can see that NewFilesystemRepository was removed from src-d/go-git since v4.0.0-rc8 (https://github.com/src-d/go-git/commit/24c1878260351d9f9f6c575cbeeb5878104d6a0e).

Example with NewFilesystemRepository is here: 
https://github.com/src-d/go-git/blob/v4.0.0-rc7/examples/open/main.go

New example is here: 
https://github.com/src-d/go-git/blob/v4.0.0-rc9/_examples/open/main.go

I hope it could help to fix the builds (until a next rc?).

**Comment by dunglas** [comment]
I think we can upgrade to the last version. Do you want to open a PR?

**Comment by aloupfor** [comment]
I tried to fix the build by updating go-git (running `govendor fetch gopkg.in/src-d/go-git.v4`) and changing `NewFilesystemRepository` method call to `PlainOpen`.

When running `calavera input_directory output_directory`, the result is:
```
panic: value method extractor.Git.Extract called using nil *Git pointer

goroutine 1 [running]:
panic(0x78b000, 0xc4202540c0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/dunglas/calavera/extractor.(*Git).Extract(0x0, 0xc4200da240, 0xc4201dc816, 0x9, 0x0, 0x0)
	<autogenerated>:1 +0xf3
main.convert(0xc4201dc816, 0x9, 0x7ffd3f7ea43e, 0x13, 0xc4201cbe20, 0x2, 0x2, 0x0)
	/home/user/workspace/go/src/github.com/dunglas/calavera/app.go:109 +0x155
main.main()
	/home/user/workspace/go/src/github.com/dunglas/calavera/app.go:53 +0x404
```

I have not been able to find out what is going on.
